### ISSUE TITLE
Parte 2 - 28/03/2023 - Merge(União) dos códigos

### ISSUE THREAD

**Issue by ArthConf** [ArthConf/Estrutura-de-Dados-I#2]
Vamos unir os códigos e testar

**Comment by ArthConf** [comment]
[file.c.txt](https://github.com/ArthConf/Estrutura-de-Dados-I/files/11094790/file.c.txt)
[file.h.txt](https://github.com/ArthConf/Estrutura-de-Dados-I/files/11094791/file.h.txt)

**Comment by Anthonygoc** [comment]
https://onlinegdb.com/1pcbfjMI9

**Comment by Anthonygoc** [comment]
https://onlinegdb.com/ChYYy4rpB

**Comment by Anthonygoc** [comment]
https://onlinegdb.com/toVZBKliR
Merge Part 1

**Comment by Anthonygoc** [comment]
https://www.onlinegdb.com/ZeX709lgB

**Comment by Anthonygoc** [comment]
system("clear");
   printf("Digite o ID: \n►");
   scanf("%d", &v[i].id);
    getchar();
   printf("Digite seu Nome: \n►");
   fgets(v[i].nome,25,stdin);
   printf("Digite sua idade: \n►");
   scanf("%d", &v[i].idd);
   printf("Digite seu Peso: \n►");
   scanf ("%f", &v[i].peso);
   printf("Digite sua Altura: \n►");
   scanf("%f", &v[i].alt);
   printf("Canhoto ou Destro \n►");
   scanf("%s",  v[i].mao);
   system("clear");

**Comment by Anthonygoc** [comment]
printf(" ______________________________\n");
      printf("ʕ•́ᴥ•̀ʔっRelatorios Aqui!!! \n");
      printf(" _________________________________\n");
      printf("|                                 \n");
      printf("|O ID: %d ✔              \n", v[i].id);
      printf("|                                 \n");
      printf("|Nome: %s      \n", v[i].nome);
      printf("|                                 \n");
      printf("|Idade: %d <---Anos                   \n", v[i].idd);
      printf("|                                 \n");
      printf("|Peso: %.2f <---Kg              \n",v[i].peso);
      printf("|                                 \n");
      printf("|Altura: %.2f <---Metros          \n",v[i].alt);
      printf("|                                 \n");
      printf("|Habilidade: %s✍            \n",v[i].mao);
      printf("|                                 \n");
      printf("|IMC: %.2f⚠         \n",IMC);
      printf("|_________________________________\n");

**Comment by ArthConf** [comment]
[file.c.txt](https://github.com/ArthConf/Estrutura-de-Dados-I/files/11096478/file.c.txt)
[file.h.txt](https://github.com/ArthConf/Estrutura-de-Dados-I/files/11096479/file.h.txt)
[main.c.txt](https://github.com/ArthConf/Estrutura-de-Dados-I/files/11096481/main.c.txt)

Merge realizado!!!

Trabalho finalizado e enviado para o Professor Constantino!

Os documentos do projeto estão disponíveis acima.
